name: BrunoZZZZZZ
on: [deployment_status]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Report PHPUnit Starting
        uses: dflydev/check-runs-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: 'ze manel'
          id: phpunit
          status: completed
