name: Zeeeee After Deployment CCCCCCCB222
on:
  deployment_status:

jobs:
  CCCCCCC:
    if: github.event.deployment_status.environment == 'Preview – nx-vercel-test-gh-action-after-deploy-app-one'
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        name: CCCCCCC
        id: create_check_run
        with:
          route: POST /repos/bmvantunes/nx-vercel-test-gh-action-after-deploy/check-runs
          name: "Test check run CCCCCCC"
          conclusion: "success"
          status: "completed"
          head_sha: ${{ github.sha }}
          output: | # The | is significant!
            title: Test check run CCCCCCCB
            summary: A summary of the test check CCCCCCCB
            images:
              - alt: Test CCCCCCCBB
                image_url: https://octodex.github.com/images/jetpacktocat.png
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
