name: BrunoZZZZZZ
on: [deployment_status]

jobs:
  build:
    steps:
      - name: Report PHPUnit Starting
        uses: dflydev/check-runs-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: phpunit
          status: in_progress
