name: Bruno
on: [deployment_status]

jobs:
  create-file:
    name: 'YESSS'
    runs-on: ubuntu-latest
    if: ${{ github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Preview – nx-vercel-test-gh-action-after-deploy-app-two' }}
    steps:
      # Create check run
      - uses: octokit/request-action@v2.x
        id: create_check_run
        with:
          route: POST /repos/bmvantunes/nx-vercel-test-gh-action-after-deploy/check-runs
          name: 'testeeeeeeeeeeeeeeeeeeee'
          sha: ${{ github.sha }}
          status: 'completed'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
