name: Zeeeee After Deployment DDDDDDD
on:
  deployment_status:

jobs:
  DDDDDDD:
    if: github.event.deployment_status.environment == 'Preview – nx-vercel-test-gh-action-after-deploy-app-one'
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        name: DDDDDDD
        id: create_check_run
        with:
          route: POST /repos/bmvantunes/nx-vercel-test-gh-action-after-deploy/check-runs
          name: "Test Benfica run DDDDDDD"
          conclusion: "success"
          status: "completed"
          head_sha: ${{ github.sha }}
          output: | # The | is significant!
            title: Test check run DDDDDDD
            summary: A summary of the test check DDDDDDD
            images:
              - alt: Test Benfica DDDDDDD
                image_url: https://sco.wikipedia.org/wiki/File:SL_Benfica_logo.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
