name: End-to-end tests
on: [deployment_status]

jobs:
  create-file:
    name: 'YESSS'
    runs-on: ubuntu-latest
    if: github.event.deployment_status.environment == 'Preview – nx-vercel-test-gh-action-after-deploy-app-one'
    steps:
      # Create check run
      - uses: octokit/request-action@v2.x
        id: create_check_run
        with:
          route: POST /repos/{owner}/{repo}/check-runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Update check run to completed, successful status
      - uses: octokit/request-action@v2.x
        id: update_check_run
        with:
          route: PATCH /repos/{owner}/{repo}/check-runs/{check_run_id}
          status: 'completed'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
