name: After Deployment
on:
  deployment_status:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm ci
    - name: Check project name
      run: echo "${{ github.event.deployment_status.target_url }}"
    - name: Print all event
      run: echo "${{ toJSON(github.event) }}"
