name: End-to-end tests
on: [deployment_status]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    if: ${{ github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Preview – nx-vercel-test-gh-action-after-deploy-app-two' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: echo "Bruno"
        # Continue the build in case of an error, as we need to set the
        # commit status in the next step, both in case of success and failure
        continue-on-error: true
      # Action does not set commit/pull reques status automatically, because it
      # is not triggered by the `push` event. So we have to set the commit
      # status manually.
      - name: Create commit status
        uses: octokit/request-action@v2.x
        id: create_status
        with:
          route: POST /repos/:repository/statuses/:sha
          repository: ${{ github.repository }}
          sha: ${{ github.sha }}
          context: test
          description: Cypress run
          conclusion: "success"
          status: "completed"
          target_url: https://dashboard.cypress.io/projects/4nc4rv/runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
