name: After Deployment
on:
  deployment_status:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
    - uses: actions/checkout@v2
    - name: Check project names
      run: echo "${{ github.event.depolyment_status.target_url }}"
    - name: Check project namesssssss
      run: echo "${{ github.event.depolyment_status }}"
    - name: Print all event
      run: echo "${{ toJSON(github.event) }}"
